CREATE TABLE IF NOT EXISTS binance_24h_tickers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    price_change DECIMAL(28,8),
    price_change_percent DECIMAL(28,8),
    weighted_avg_price DECIMAL(28,8),
    prev_close_price DECIMAL(28,8),
    last_price DECIMAL(28,8),
    last_qty DECIMAL(28,8),
    bid_price DECIMAL(28,8),
    bid_qty DECIMAL(28,8),
    ask_price DECIMAL(28,8),
    ask_qty DECIMAL(28,8),
    open_price DECIMAL(28,8),
    high_price DECIMAL(28,8),
    low_price DECIMAL(28,8),
    volume DECIMAL(20, 8),
    quote_volume DECIMAL(20, 8),
    open_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    close_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    first_id BIGINT,
    last_id BIGINT,
    count BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
